language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script: 
  - dotnet restore csharp.csproj
  - dotnet build csharp.csproj 
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1